### PR TITLE
Ported → N2O.

### PR DESCRIPTION
**Pull request by am-kantox**

### CODE REVIEW

**Comment by 5HT** [comment]
Do I need also populate and inject this snippet into all synrc libraries ?

**Comment by am-kantox** [comment]
Eh. It depends.

I assumed `n2o` is kinda “master” one, so `use N2O, with: [:n2o, :nitro]` will inject records via imports and aliases for _both_ `n2o` and `nitro`.

https://hexdocs.pm/elixir/Kernel.html#use/2

**Comment by am-kantox** [comment]
https://github.com/o7/sample/blob/master/lib/index.ex#L2

To inject `nitro` only, one might `use N2O, with: [:nitro]`. Maybe it makes sense to rename `with:` to `only:` to make it more explicit. Or to move the whole `__using__/1` macro into some separated module, like `N2O.Lib`.

**Comment by 5HT** [comment]
It's not that N2O master one, e.g. data-only apps depens then on KVX, this if you accept is an other root. I like the power of `with: ` syntax and want to include that into KVX as well. And we have console HTML preprocessors that depend only on NITRO and even not KVX or N2O. MADness! :-)

**Comment by am-kantox** [comment]
Man, there is no `with` syntax. It’s a `Keyword.t()` argument in call to `__using__/1` macro. You might pass any `Keyword.t()` list there, e.g. `[{:all, true}, {:except, :nitro}, {:with_kv, :redis}]`. The code simply uses this list as a plain old good parameter.

**Comment by 5HT** [comment]
I meant particular N2O DSL just committed. But I noted!

**Pull request merged**
