### PR TITLE
Extracted imports / aliases into `use Ported`.

### PR DESCRIPTION
**Pull request by am-kantox**

### CODE REVIEW

**Comment by 5HT** [comment]
Ooops, This code is already in conflict! I will add you as collaborator so feel free to resolve by yourself. Small note: that WE ARE ALL CAPS like in SPARTA! (regarding module names :-)

**Comment by 5HT** [comment]
Just Wow!

**Comment by am-kantox** [comment]
Now. It’s not a must-have change but I think it’d better to fully encapsulate the behaviour into `use ___` to make users not worry about how exactly it’s implemented under the hood. Maybe also the default list of includes would make sense when no `with: ` argument to `use` is supplied. I dunno :)

**Comment by am-kantox** [comment]
Maybe it’d also make sense to move `Ported` module somewhere into `N2O` to make the usage more transparent.

**Comment by 5HT** [comment]
Yeah exactly noted about that in twitter. The best way I see is to include it in underlying libs, so when I use `import N2O`, or `use N2O` all macros are being expanded from that library. Not to carry Ported at a top level.

Wow, that was fast. Added you to N2O you can try to push there your experiments.

**Comment by am-kantox** [comment]
`use N20` is way more flexible (compared to `import` which only imports functions/macros) because it allows you to inject literally _any_ code you want into the calling module.

**Comment by 5HT** [comment]
That what we need, right!

**Pull request merged**
